application:
  name: nixmodules
  releaseChannels:
    - name: canary
      constants:
        - name: name
          string:
            value: canary
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: tarpit
      constants:
        - name: name
          string:
            value: tarpit
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: global
      constants:
        - name: name
          string:
            value: global
      preconditions:
        - manualApproval: {}
        - releaseChannelStable:
            releaseChannel: canary
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: hacker
      constants:
        - name: name
          string:
            value: hacker
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: teams
      constants:
        - name: name
          string:
            value: teams
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: asia-a
      constants:
        - name: name
          string:
            value: asia-a
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
    - name: asia-b
      constants:
        - name: name
          string:
            value: asia-b
      preconditions:
        - releaseChannelStable:
            releaseChannel: global
      runtimes:
        - name: config-raw
          runtime: marine-cycle-160323--govalctl-config-raw
          type: EXTENSION
